TrouveTout_route:
    resource: "@TrouveToutBundle/Controller"
    type: annotation
    prefix: /{_locale}/
    requirements:
      _locale: en|fr

login_check:
    pattern:   /{_locale}/login_check
 
logout:
    pattern:   /{_locale}/logout
