parameters:
#    TrouveTout.example.class: Ukratio\TrouveToutBundle\Example

services:

  # Forms events
  TrouveTout.ElementEventSubscriber:
    class: Ukratio\TrouveToutBundle\Form\EventListener\ElementEventSubscriber
    arguments: [@form.factory, @TrouveTout.CaractTypeManager]

  TrouveTout.ConceptEventSubscriber:
    class: Ukratio\TrouveToutBundle\Form\EventListener\ConceptEventSubscriber
    arguments: [@form.factory, @TrouveTout.repository.concept, @doctrine.orm.entity_manager, @TrouveTout.form.concept_concept]

  TrouveTout.CaractEventSubscriber:
    class: Ukratio\TrouveToutBundle\Form\EventListener\CaractEventSubscriber
    arguments: [@TrouveTout.repository.element, @TrouveTout.CaractTypeManager, @form.factory, %kernel.root_dir%]

  # Services
  TrouveTout.ElementManager:
    class: Ukratio\TrouveToutBundle\Service\ElementManager
    arguments: [%kernel.root_dir%]

  TrouveTout.CaractTypeManager:
    class: Ukratio\TrouveToutBundle\Service\CaractTypeManager
    arguments: [@form.factory, @TrouveTout.repository.concept, @TrouveTout.repository.element, @TrouveTout.ElementManager, @tool.data_checking, %kernel.root_dir%]

  TrouveTout.PrototypeManager:
    class: Ukratio\TrouveToutBundle\Service\PrototypeManager
    arguments: []

  TrouveTout.ConceptFormManager:
    class: Ukratio\TrouveToutBundle\Service\ConceptFormManager
    arguments: [@form.factory, @doctrine.orm.entity_manager, @TrouveTout.repository.concept]

  TrouveTout.Tools:
    class: Ukratio\TrouveToutBundle\Service\Tools
    arguments: [@doctrine.orm.entity_manager, @TrouveTout.repository.concept]

  # Forms Types
  TrouveTout.form.caract:
    class: Ukratio\TrouveToutBundle\Form\Type\CaractType
    arguments: [@TrouveTout.CaractTypeManager]
    tags:
      - {name: form.type, alias: TrouveTout_Caract}

  TrouveTout.form.element:
    class: Ukratio\TrouveToutBundle\Form\Type\ElementType
    arguments: [@TrouveTout.ElementEventSubscriber]
    tags:
      - {name: form.type, alias: TrouveTout_Element}

  TrouveTout.form.concept:
    abstract: true
    arguments: [@TrouveTout.ConceptEventSubscriber, @TrouveTout.form.caract, @TrouveTout.PrototypeManager]

  TrouveTout.form.set:
    class: Ukratio\TrouveToutBundle\Form\Type\SetType
    parent: TrouveTout.form.concept
    tags:
      - {name: form.type, alias: TrouveTout_Set}

  TrouveTout.form.category:
    class: Ukratio\TrouveToutBundle\Form\Type\CategoryType
    parent: TrouveTout.form.concept
    tags:
      - {name: form.type, alias: TrouveTout_Category}

  TrouveTout.form.research:
    class: Ukratio\TrouveToutBundle\Form\Type\ResearchType
    parent: TrouveTout.form.concept
    tags:
      - {name: form.type, alias: TrouveTout_Research}

  TrouveTout.form.concept_concept:
    class: Ukratio\TrouveToutBundle\Form\Type\ConceptConceptType
    arguments: [@TrouveTout.form.sorted_concept]
    tags:
      - {name: form.type, alias: TrouveTout_ConceptConcept}

  TrouveTout.form.sorted_concept:
    class: Ukratio\TrouveToutBundle\Form\Type\SortedConceptType
    arguments: [@TrouveTout.repository.concept, @doctrine.orm.entity_manager]
    tags:
      - {name: form.type, alias: TrouveTout_SortedConcept}

  # Repositories
  TrouveTout.repository.concept:
    class: Ukratio\TrouveToutBundle\Entity\ConceptRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments: ['TrouveToutBundle:Concept']
    calls:
      - [setArrayHandling, [@tool.array_handling]]


  TrouveTout.repository.caract:
    class: Ukratio\TrouveToutBundle\Entity\CaractRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments: ['TrouveToutBundle:Caract']

  TrouveTout.repository.element:
    class: Ukratio\TrouveToutBundle\Entity\ElementRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments: ['TrouveToutBundle:Element']


# TUTORIAL SERVICE

  TrouveTout.tutorial.repository.concept:
    class: Ukratio\TrouveToutBundle\Tutorial\ConceptTutorialRepository
    arguments: [@translator]

  TrouveTout.tutorial.form.sorted_concept:
    class: Ukratio\TrouveToutBundle\Form\Type\SortedConceptType
    arguments: [@TrouveTout.tutorial.repository.concept, @doctrine.orm.entity_manager]
    tags:
      - {name: form.type, alias: TrouveTout_SortedConcept}

  TrouveTout.tutorial.form.concept_concept:
    class: Ukratio\TrouveToutBundle\Form\Type\ConceptConceptType
    arguments: [@TrouveTout.tutorial.form.sorted_concept]
    tags:
      - {name: form.type, alias: TrouveTout_ConceptConcept}

  TrouveTout.tutorial.ConceptEventSubscriber:
    class: Ukratio\TrouveToutBundle\Form\EventListener\ConceptEventSubscriber
    arguments: [@form.factory, @TrouveTout.tutorial.repository.concept, @doctrine.orm.entity_manager, @TrouveTout.tutorial.form.concept_concept]

  TrouveTout.tutorial.form.concept:
    abstract: true
    arguments: [@TrouveTout.tutorial.ConceptEventSubscriber, @TrouveTout.form.caract, @TrouveTout.PrototypeManager]

  TrouveTout.tutorial.form.category:
    class: Ukratio\TrouveToutBundle\Form\Type\CategoryType
    parent: TrouveTout.tutorial.form.concept
    tags:
      - {name: form.type, alias: TrouveTout_Tutorial_Category}

