parameters:
#    TrouveTout.example.class: Ukratio\TrouveToutBundle\Example

services:

  TrouveTout.ElementManager:
    class: Ukratio\TrouveToutBundle\Service\ElementManager
    arguments: [%kernel.root_dir%]

  TrouveTout.CaractTypeManager:
    class: Ukratio\TrouveToutBundle\Service\CaractTypeManager
    arguments: [@form.factory, @TrouveTout.repository.concept, @TrouveTout.repository.element, @TrouveTout.ElementManager, @tool.data_checking, %kernel.root_dir%]

  TrouveTout.ConceptFormManager:
    class: Ukratio\TrouveToutBundle\Service\ConceptFormManager
    arguments: [@form.factory, @doctrine.orm.entity_manager, @TrouveTout.repository.concept]

  TrouveTout.Tools:
    class: Ukratio\TrouveToutBundle\Service\Tools
    arguments: [@doctrine.orm.entity_manager, @TrouveTout.repository.concept]

  TrouveTout.form.caract:
    class: Ukratio\TrouveToutBundle\Form\Type\CaractType
    arguments: [@TrouveTout.repository.concept, @TrouveTout.repository.caract, @TrouveTout.repository.element, @TrouveTout.CaractTypeManager,  @tool.data_checking]
    tags:
      - {name: form.type, alias: TrouveTout_Caract}

  TrouveTout.form.element:
    class: Ukratio\TrouveToutBundle\Form\Type\ElementType
    arguments: [@TrouveTout.repository.concept, @TrouveTout.repository.element, @TrouveTout.CaractTypeManager]
    tags:
      - {name: form.type, alias: TrouveTout_Element}

  TrouveTout.form.set:
    class: Ukratio\TrouveToutBundle\Form\Type\SetType
    arguments: [@TrouveTout.repository.concept, @doctrine.orm.entity_manager, @TrouveTout.form.caract, @TrouveTout.CaractTypeManager]
    tags:
      - {name: form.type, alias: TrouveTout_Set}

  TrouveTout.form.category:
    class: Ukratio\TrouveToutBundle\Form\Type\CategoryType
    arguments: [@TrouveTout.repository.concept, @TrouveTout.repository.caract, @TrouveTout.repository.element, @TrouveTout.ElementManager, @form.factory, @doctrine.orm.entity_manager]
    tags:
      - {name: form.type, alias: TrouveTout_Category}

  TrouveTout.form.research:
    class: Ukratio\TrouveToutBundle\Form\Type\ResearchType
    arguments: [@TrouveTout.repository.concept, @TrouveTout.repository.caract, @TrouveTout.repository.element, @TrouveTout.ElementManager, @form.factory, @doctrine.orm.entity_manager]
    tags:
      - {name: form.type, alias: TrouveTout_Research}

  TrouveTout.form.concept_concept:
    class: Ukratio\TrouveToutBundle\Form\Type\ConceptConceptType
    arguments: [@TrouveTout.repository.concept, @doctrine.orm.entity_manager]
    tags:
      - {name: form.type, alias: TrouveTout_ConceptConcept}

  TrouveTout.form.sorted_concept:
    class: Ukratio\TrouveToutBundle\Form\Type\SortedConceptType
    arguments: [@TrouveTout.repository.concept, @doctrine.orm.entity_manager]
    tags:
      - {name: form.type, alias: TrouveTout_SortedConcept}

  TrouveTout.repository.concept:
    class: Ukratio\TrouveToutBundle\Entity\ConceptRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments: ['TrouveToutBundle:Concept']
    calls:
      - [setArrayHandling, [@tool.array_handling]]


  TrouveTout.repository.caract:
    class: Ukratio\TrouveToutBundle\Entity\CaractRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments: ['TrouveToutBundle:Caract']

  TrouveTout.repository.element:
    class: Ukratio\TrouveToutBundle\Entity\ElementRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments: ['TrouveToutBundle:Element']


# TUTORIAL SERVICE

  TrouveTout.tutorial.form.category:
    class: Ukratio\TrouveToutBundle\Form\Type\CategoryType
    arguments: [@TrouveTout.tutorial.repository.concept, @TrouveTout.repository.caract, @TrouveTout.repository.element, @TrouveTout.ElementManager, @form.factory, @doctrine.orm.entity_manager]

  TrouveTout.tutorial.form.concept_concept:
    class: Ukratio\TrouveToutBundle\Form\Type\ConceptConceptType
    arguments: [@TrouveTout.tutorial.repository.concept, @doctrine.orm.entity_manager]

  TrouveTout.tutorial.repository.concept:
    class: Ukratio\TrouveToutBundle\Tutorial\ConceptTutorialRepository
    arguments: [@translator]
