parameters:
#    TrouveTout.example.class: Ukratio\TrouveToutBundle\Example

services:
#    TrouveTout.example:
#        class: %TrouveTout.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    TrouveTout.ConceptFormManager:
        class: Ukratio\TrouveToutBundle\Service\ConceptFormManager
        arguments: [@form.factory, @doctrine.orm.entity_manager, @TrouveTout.repository.concept]

    TrouveTout.Tools:
        class: Ukratio\TrouveToutBundle\Service\Tools
        arguments: [@doctrine.orm.entity_manager, @TrouveTout.repository.concept]

    TrouveTout.ConceptTypeFunctions:
        class: Ukratio\TrouveToutBundle\Service\ConceptTypeFunctions

    TrouveTout.form.caract:
        class: Ukratio\TrouveToutBundle\Form\Type\CaractType
        arguments: [@doctrine.orm.entity_manager, @TrouveTout.repository.concept, @tool.data_checking]
        tags: 
            - {name: form.type, alias: TrouveTout_Caract}

    TrouveTout.form.element:
        class: Ukratio\TrouveToutBundle\Form\Type\ElementType
        arguments: [@doctrine.orm.entity_manager, @TrouveTout.repository.concept]
        tags: 
            - {name: form.type, alias: TrouveTout_Element}

    TrouveTout.form.set:
        class: Ukratio\TrouveToutBundle\Form\Type\SetType
        arguments: [@doctrine.orm.entity_manager, @TrouveTout.ConceptTypeFunctions]
        tags: 
            - {name: form.type, alias: TrouveTout_Set}

    TrouveTout.form.category:
        class: Ukratio\TrouveToutBundle\Form\Type\CategoryType
        arguments: [@doctrine.orm.entity_manager, @TrouveTout.ConceptTypeFunctions]
        tags: 
            - {name: form.type, alias: TrouveTout_Category}

    TrouveTout.form.research:
        class: Ukratio\TrouveToutBundle\Form\Type\ResearchType
        arguments: [@doctrine.orm.entity_manager, @TrouveTout.ConceptTypeFunctions]
        tags: 
            - {name: form.type, alias: TrouveTout_Research}

    TrouveTout.form.category_choice:
        class: Ukratio\TrouveToutBundle\Form\Type\CategoryChoiceType
        arguments: [@doctrine.orm.entity_manager]
        tags: 
            - {name: form.type, alias: TrouveTout_CategoryChoice}

    TrouveTout.form.concept_concept:
        class: Ukratio\TrouveToutBundle\Form\Type\ConceptConceptType
        arguments: [@doctrine.orm.entity_manager, @tool.array_handling]
        tags: 
            - {name: form.type, alias: TrouveTout_ConceptConcept}

    TrouveTout.repository.concept:
        class: Ukratio\TrouveToutBundle\Entity\ConceptRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: ['TrouveToutBundle:Concept']
        calls: 
          - [setArrayHandling, [@tool.array_handling]]
