<?php

namespace Ukratio\TrouveToutBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Ukratio\TrouveToutBundle\Entity\Discriminator;
use Doctrine\ORM\QueryBuilder;

/**
 * ConceptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptRepository extends EntityRepository
{

    public function findByIdWithCaract($id)
    {
        
        $queryBuilder = $this->createQueryBuilder('concept')
                             ->where('concept.id = :id')
                             ->setParameter('id', $id)
                             ->leftJoin('concept.caracts', 'caracts')
                             ->addSelect('caracts')
                             ->leftJoin('caracts.value', 'element')
                             ->addSelect('element')
                             ->leftJoin('concept.moreGeneralConceptConcepts', 'generalConcept')
                             ->addSelect('generalConcept');

        return $queryBuilder->getQuery()->getResult()[0];
    }


    public function count()
    {
        $querybuilder = $this->createQueryBuilder('a')
                             ->select('COUNT(a)');

        return (int) $querybuilder->getQuery()
                                  ->getSingleScalarResult();
    }

    public function findMoreGeneralCategories(Concept $concept)
    {
        $queryBuilder = $this->createQueryBuilder('concept')
                             ->leftJoin('concept.moreSpecificConceptConcepts', 'ConceptConcept')
                             ->where('ConceptConcept.moreSpecific = :id')
                             ->setParameter('id', $concept->getId());
        $queryBuilder = $this->whereIsCategory($queryBuilder);

        return $queryBuilder->getQuery()->getResult();
    }

    public function findAllCategories()
    {
        return $this->QueryBuilderAllCategories()->getQuery()->getResult();
    }

    public function QueryBuilderAllCategories()
    {
        $queryBuilder = $this->createQueryBuilder('concept');
        $queryBuilder = $this->whereIsCategory($queryBuilder);
        
        return $queryBuilder;
    }

    public function findNamedSet()
    {
        $queryBuilder = $this->createQueryBuilder('concept');
        $queryBuilder = $this->whereIsNamedSet($queryBuilder);
        
        return $queryBuilder->getQuery()->getResult();
    }

    public function QueryBuilderNamedSet()
    {
        $queryBuilder = $this->createQueryBuilder('concept');
        $queryBuilder = $this->whereIsNamedSet($queryBuilder);
        
        return $queryBuilder;
    }

    public function whereIsNamedSet(QueryBuilder $queryBuilder)
    {
        $queryBuilder->andWhere('concept.name is NOT NULL');
        $queryBuilder = $this->whereIsSet($queryBuilder);

        return $queryBuilder;
    }

    public function whereIsSet(QueryBuilder $queryBuilder)
    {
        $queryBuilder->andWhere('concept.type = :type')
                     ->setParameter('type', Discriminator::$Set->getName());
        return $queryBuilder;
    }

    public function whereIsCategory(QueryBuilder $queryBuilder)
    {
        $queryBuilder->andWhere('concept.type = :type')
                     ->setParameter('type', Discriminator::$Category->getName());
        return $queryBuilder;
    }
}
